#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Assemble the single self-contained game.html (M0 build).

Inputs:  game/shell.html, game/src/*.js (ordered), game/timeline.json,
         assets/fonts/Lalezar-Regular.ttf (extracted from animatic.html).
Output:  game.html at repo root — opens from file://, no network at runtime.
The timeline JSON is injected verbatim (lyrics byte-exact, generated by
tools/gen_timeline.py from docs/timing-map.md; never hand-edited).
"""
import base64, io, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'game', 'src')
SHELL = io.open(os.path.join(ROOT, 'game', 'shell.html'), encoding='utf-8').read()
TL = json.load(io.open(os.path.join(ROOT, 'game', 'timeline.json'), encoding='utf-8'))
FONT = os.path.join(ROOT, 'assets', 'fonts', 'Lalezar-Regular.ttf')

CSS = """
html,body{margin:0;padding:0;height:100%;background:#070b16;overflow:hidden;touch-action:none;-webkit-user-select:none;user-select:none}
canvas{display:block;background:#0d1018}
@font-face{font-family:Lalezar;src:url(data:font/ttf;base64,__FONTB64__) format('truetype');font-weight:normal}
"""

def main():
    modules = []
    for fn in sorted(os.listdir(SRC)):
        if fn.endswith('.js'):
            modules.append('/* ==== %s ==== */\n' % fn + io.open(os.path.join(SRC, fn), encoding='utf-8').read())
    game_js = '\n'.join(modules)
    # inject timeline as a JS const (JSON dumped with ensure_ascii=False → byte-exact Persian)
    tl_js = 'const TIMELINE = ' + json.dumps(TL, ensure_ascii=False, separators=(',', ':')) + ';'
    game_js = tl_js + '\n' + game_js
    # syntax gate: refuse to build on invalid JS (node --check via stdin)
    import subprocess
    try:
        p = subprocess.run(['node', '--check', '-'],
                           input=game_js.encode('utf-8'),
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except FileNotFoundError:
        print('WARNING: node not found — bundle NOT syntax-checked', file=sys.stderr)
        p = None
    if p is not None and p.returncode != 0:
        print('SYNTAX ERROR in bundle:\n' + p.stderr.decode('utf-8', 'replace'), file=sys.stderr)
        sys.exit(1)
    # embed font
    font_b64 = base64.b64encode(open(FONT, 'rb').read()).decode('ascii')
    css = CSS.replace('__FONTB64__', font_b64)
    html = SHELL.replace('/*__CSS__*/', css).replace('/*__GAME__*/', game_js)
    out = os.path.join(ROOT, 'game.html')
    io.open(out, 'w', encoding='utf-8').write(html)
    # sanity: timeline lines byte-exact inside output
    for s in TL['steps']:
        assert s['line'] in html, 'line %d missing' % s['n']
    print('built %s (%.1f KB, %d modules, 36 steps byte-exact)' % (
        out, os.path.getsize(out) / 1024, len(modules)))

if __name__ == '__main__':
    main()
